version: 2.1

# Define reusable orbs (if needed)
orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: cimg/node:14.17  # Use an appropriate Docker image

    environment:
      # Set any environment variables
      CUSTOM_ENV_VAR: "my-value"

    steps:
      - checkout  # Step to check out source code

      - restore_cache:  # Step to restore cache
          keys:
            - node-dependencies-{{ checksum "package-lock.json" }}
            # You can specify more fallback keys

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:  # Step to save cache after successful npm install
          paths:
            - ./node_modules
          key: node-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Additional Commands
          command: |
            echo "You can run additional commands here"
            # Add more commands as needed

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
